- type: entity
  id: CEWindowBase
  abstract: true
  parent: Window
  categories: [ ForkFiltered ]
  components:
  - type: Transform
    noRot: true
  - type: Sprite
    drawdepth: Mobs
  - type: Icon
    state: full
  - type: IconSmooth
    key: CEwindow
    base: window
  - type: PlacementReplacement
    key: walls
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.5,-0.3,0.5,0.7"
        mask:
        - FullTileMask
        layer:
        - GlassLayer
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: Glass
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 150 #excess damage (nuke?). avoid computational cost of spawning entities.
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: WindowShatter
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: CEZLevelHighGround

- type: entity
  id: CEBaseWindowFrame
  categories: [ ForkFiltered ]
  parent: BaseStructure
  abstract: true
  description: Provides a nice breeze. The gap looks big enough to climb through.
  placement:
    mode: SnapgridCenter
    snap:
    - Window
  components:
  - type: Sprite
    drawdepth: Mobs
  - type: Icon
    state: full
  - type: IconSmooth
    key: CEwindow
    base: window
  - type: PlacementReplacement
    key: walls
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.5,-0.5,0.5,0.5"
        mask:
        - FullTileMask
        layer:
        - HalfWallLayer
  - type: Appearance
  - type: Climbable

- type: entity
  id: CEBaseWindowFrameBroken
  parent: CEBaseWindowFrame
  abstract: true
  description: Broken window. You can get in, but the sharp splinters will tear your skin.
  components:
  - type: StepTrigger
    requiredTriggeredSpeed: 0
    intersectRatio: 0.2
  - type: Slippery
    slipSound:
      collection: GlassCrack
    slipData:
      launchForwardsMultiplier: 0
  - type: TriggerOnStepTrigger
  - type: DamageOnTrigger
    damage:
      types:
        Slash: 10
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.5,-0.5,0.5,0.5"
        mask:
        - FullTileMask
        layer:
        - HalfWallLayer
      slips: # For stun & damage
        shape:
          !type:PhysShapeAabb
          bounds: "-0.3,-0.3,0.3,0.3"
        hard: false
        mask:
          - FullTileLayer
