- type: entity
  id: CECookerBase
  parent: BaseStorageItem
  categories: [ ForkFiltered ]
  abstract: true
  components:
  - type: Sprite
    noRot: true
  - type: Appearance
  - type: GenericVisualizer
    visuals:
      enum.StorageVisuals.Open:
        base:
          True: { state: opened }
          False: { state: closed }
      enum.CECookingVisuals.Cooking:
        cook:
          True: { visible: true }
          False: { visible: false }
      enum.CECookingVisuals.Burning:
        burn:
          True: { visible: true }
          False: { visible: false }
  - type: ContainerContainer
    containers:
      storagebase: !type:Container
        ents: []
  - type: Storage
    maxItemSize: Normal
    grid:
    - 0,0,3,3
    whitelist:
      components:
        - Food
        - Edible
      tags:
        - CEFitInFryingPan #Todo delete this tag from game
    ignorelist:
      components:
        - CEFoodHolder
        - FoodSequenceStartPoint
        - Injector
        - SolutionTransfer
        - Sharp
  - type: CEFoodCooker
    containerId: storagebase
  - type: Temperature
  - type: DoAfter
  - type: AmbientSound
    enabled: false
    volume: 5
    range: 5
